//Given two strings s and t which consist of only lowercase letters.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Find the letter that was added in t.
//
//Example:
//
//Input:
//s = "abcd"
//t = "abcde"
//
//Output:
//e
//
//Explanation:
//'e' is the letter that was added.

class Solution {
public:
    char findTheDifference(string s, string t) {
        
        vector<int> sc(26, 0);
        vector<int> tc(26, 0);
        for(char l : s) {
            sc[l - 'a'] += 1;
        }
        for(char l : t) {
            tc[l - 'a'] += 1;
        }
        for(int i = 0; i < 26; i++) {
            if(sc[i] != tc[i]) {
                return (i + 'a');
            }
        }
        return 'a';
        
        /*
        int x = 0;
        for(char l : s) {
            x ^= (l - 'a');
        }
        for(char l : t) {
            x ^= (l - 'a');
        }
        return (x + 'a');
        */
        /*
        for(char l : t) {
            if(count(t.begin(), t.end(), l) > count(s.begin(), s.end(), l)) {
                return l;
            }
        }
        return 'a';
        */
    }
};